#include "common.h"

INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __13AiPunchReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__13AiPunchReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getBestTarget__13AiPunchReflexR2AiRf);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getTargetScore__13AiPunchReflexR2AiP7Monster);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__13AiPunchReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__13AiPunchReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__13AiPunchReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", selectPunch__13AiPunchReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", punch__13AiPunchReflexR2Aii);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__13AiPunchReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __11AiBatReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__11AiBatReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getBestTarget__11AiBatReflexR2AiRf);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getTargetScore__11AiBatReflexR2AiP7Monster);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__11AiBatReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__11AiBatReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__11AiBatReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", selectSwipe__11AiBatReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", swipe__11AiBatReflexR2Aii);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__11AiBatReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __16AiFireProjectile);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__16AiFireProjectileR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getBestTarget__16AiFireProjectileR2AiRf);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getTargetRelevance__16AiFireProjectileR2AiP7Monster);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__16AiFireProjectileR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__16AiFireProjectileR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__16AiFireProjectileR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__16AiFireProjectileR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __15AiGrappleReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__15AiGrappleReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getBestTarget__15AiGrappleReflexR2AiRf);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__15AiGrappleReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__15AiGrappleReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__15AiGrappleReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__15AiGrappleReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __13AiBlockReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__13AiBlockReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__13AiBlockReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__13AiBlockReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__13AiBlockReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__13AiBlockReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __15AiCounterReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__15AiCounterReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__15AiCounterReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__15AiCounterReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__15AiCounterReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__15AiCounterReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __14AiThrashReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__14AiThrashReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__14AiThrashReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__14AiThrashReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__14AiThrashReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__14AiThrashReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __15AiDisposeReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__15AiDisposeReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__15AiDisposeReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__15AiDisposeReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__15AiDisposeReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__15AiDisposeReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __13AiSmashReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__13AiSmashReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__13AiSmashReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__13AiSmashReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__13AiSmashReflexR2Ai);
void exitAction__13AiSmashReflexR2Ai(void *self) __asm__("exitAction__13AiSmashReflexR2Ai");
void exitAction__13AiSmashReflexR2Ai(void *self)
{
}
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __14AiThrowRecover);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__14AiThrowRecoverR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__14AiThrowRecoverR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__14AiThrowRecoverR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__14AiThrowRecoverR2Ai);
void exitAction__14AiThrowRecoverR2Ai(void *self) __asm__("exitAction__14AiThrowRecoverR2Ai");
void exitAction__14AiThrowRecoverR2Ai(void *self)
{
}
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __13AiThrowPickup);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__13AiThrowPickupR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getBestTarget__13AiThrowPickupR2AiRf);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__13AiThrowPickupR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__13AiThrowPickupR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__13AiThrowPickupR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__13AiThrowPickupR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __13AiStompReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__13AiStompReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__13AiStompReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__13AiStompReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__13AiStompReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__13AiStompReflexR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __11AiRamAttack);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__11AiRamAttackR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getBestTarget__11AiRamAttackR2AiRf);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__11AiRamAttackR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__11AiRamAttackR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__11AiRamAttackR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__11AiRamAttackR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __14AiCrowdControl);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__14AiCrowdControlR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getBestTarget__14AiCrowdControlR2AiRf);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__14AiCrowdControlR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__14AiCrowdControlR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__14AiCrowdControlR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__14AiCrowdControlR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __15AiSpecialAttack);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__15AiSpecialAttackR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getBestTarget__15AiSpecialAttackR2AiRf);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__15AiSpecialAttackR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__15AiSpecialAttackR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__15AiSpecialAttackR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__15AiSpecialAttackR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __14AiDetonateHead);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__14AiDetonateHeadR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getBestTarget__14AiDetonateHeadR2AiRf);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__14AiDetonateHeadR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__14AiDetonateHeadR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__14AiDetonateHeadR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__14AiDetonateHeadR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __7AiTaunt);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__7AiTauntR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__7AiTauntR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__7AiTauntR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__7AiTauntR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", exitAction__7AiTauntR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __12AiPutOutFire);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getEntryRelevance__12AiPutOutFireR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getExitRelevance__12AiPutOutFireR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", enterAction__12AiPutOutFireR2Ai);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", updateAction__12AiPutOutFireR2Ai);
void exitAction__12AiPutOutFireR2Ai(void *self) __asm__("exitAction__12AiPutOutFireR2Ai");
void exitAction__12AiPutOutFireR2Ai(void *self)
{
}
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$12AiPutOutFire);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$7AiTaunt);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$14AiDetonateHead);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$15AiSpecialAttack);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$14AiCrowdControl);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$11AiRamAttack);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$13AiStompReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$13AiThrowPickup);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$14AiThrowRecover);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$13AiSmashReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$15AiDisposeReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$14AiThrashReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$15AiCounterReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$13AiBlockReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$15AiGrappleReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$16AiFireProjectile);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$11AiBatReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", _vt$13AiPunchReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf13AiPunchReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf11AiBatReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf16AiFireProjectile);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf15AiGrappleReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf13AiBlockReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf15AiCounterReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf14AiThrashReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf15AiDisposeReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf13AiSmashReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf14AiThrowRecover);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf13AiThrowPickup);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf13AiStompReflex);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf11AiRamAttack);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf14AiCrowdControl);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf15AiSpecialAttack);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf14AiDetonateHead);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf7AiTaunt);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", __tf12AiPutOutFire);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", getMaxLevel__11HealthMeter);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", func_0010DB98);
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", inFov__9EnemyInfof);
int inLos__9EnemyInfo(void *self) __asm__("inLos__9EnemyInfo");
int inLos__9EnemyInfo(void *self)
{
    return *(int *)((char *)self + 0x20);
}
INCLUDE_ASM("asm/nonmatchings/game/AiReflex", func_0010DBC8);
