#include "common.h"

INCLUDE_ASM("asm/nonmatchings/game/Hud", initBefore__3Hudi);
INCLUDE_ASM("asm/nonmatchings/game/Hud", initAfter__3Hudi);
INCLUDE_ASM("asm/nonmatchings/game/Hud", initForReplay__3Hud);
INCLUDE_ASM("asm/nonmatchings/game/Hud", update__3Hud);
INCLUDE_ASM("asm/nonmatchings/game/Hud", parseHudElements__3HudP9_hierhead);
INCLUDE_ASM("asm/nonmatchings/game/Hud", print__3Hud);
INCLUDE_ASM("asm/nonmatchings/game/Hud", buildPacketHead__3HudP6QwData);
INCLUDE_ASM("asm/nonmatchings/game/Hud", dmaPacket__3Hud);
INCLUDE_ASM("asm/nonmatchings/game/Hud", buildSeparator__3Hud);
INCLUDE_ASM("asm/nonmatchings/game/Hud", addHealthIndicators__3Hud);
INCLUDE_ASM("asm/nonmatchings/game/Hud", drawHealthIcon__3HudP7Monsteri);
INCLUDE_ASM("asm/nonmatchings/game/Hud", drawBossHealthBar__3Hudf);
INCLUDE_ASM("asm/nonmatchings/game/Hud", registerComboHit__3Hud);
INCLUDE_ASM("asm/nonmatchings/game/Hud", registerStaminaCredit__3Hudi);
INCLUDE_ASM("asm/nonmatchings/game/Hud", registerHealthCredit__3Hudi);
INCLUDE_ASM("asm/nonmatchings/game/Hud", addMessage__3Hudii);
INCLUDE_ASM("asm/nonmatchings/game/Hud", updateMessage__3Hud);
INCLUDE_ASM("asm/nonmatchings/game/Hud", addTextBoxMessage__3Hudi);
INCLUDE_ASM("asm/nonmatchings/game/Hud", updateTextBoxMessage__3Hud);
INCLUDE_ASM("asm/nonmatchings/game/Hud", MonsterNewNames_006EAA78);
INCLUDE_ASM("asm/nonmatchings/game/Hud", initBefore__12Letterboxing);
INCLUDE_ASM("asm/nonmatchings/game/Hud", initAfter__12Letterboxing);
INCLUDE_ASM("asm/nonmatchings/game/Hud", setEnabled__12Letterboxingb);
INCLUDE_ASM("asm/nonmatchings/game/Hud", setLetterboxCS__12LetterboxingP9_hierhead);
INCLUDE_ASM("asm/nonmatchings/game/Hud", update__12Letterboxing);
INCLUDE_ASM("asm/nonmatchings/game/Hud", __static_initialization_and_destruction_0_00147118);
INCLUDE_ASM("asm/nonmatchings/game/Hud", _GLOBAL_$I$gLowStaminaThreshold);
