#include "common.h"

INCLUDE_ASM("asm/nonmatchings/game/TankPickup", __10TankPickup);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", initAfterDbLoad__10TankPickup);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", setTrans__10TankPickupR8_fvector);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", takeHit__10TankPickupP8_fvectorfi);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", drop__10TankPickup);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", kill__10TankPickup);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", fire__10TankPickupR7GamePad);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", update__10TankPickup);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", updateLeadBehavior__10TankPickupR7GamePad);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", updateFollowBehavior__10TankPickupR7GamePad);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", updateAttackBehavior__10TankPickupR7GamePad);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", enterState__10TankPickupQ214MilitaryPickup5State);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", _vt$10TankPickup);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", leadFormation__10TankPickup);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", followFormation__10TankPickup);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", resignFormation__10TankPickup);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", func_001D0398);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", func_001D03A8);
INCLUDE_ASM("asm/nonmatchings/game/TankPickup", __tf10TankPickup);
