#!/usr/bin/env python3
"""Generate build.ninja for the WotM decomp. Run inside WSL/Linux.

    python3 configure.py            # write build.ninja (runs splat first if asm/ is missing)
    python3 configure.py --split    # force a fresh splat split
    ninja                           # build + checksum against the retail binary
"""
import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent
YAML = 'SCUS_971.97.yaml'
BASENAME = 'SCUS_971.97'
TARGET_ROM = f'{BASENAME}.rom'
RETAIL_ELF = 'disc/SCUS_971.97'
CROSS = 'mips-linux-gnu-'
RETAIL_ROM_SIZE = 0x5F8B44  # PT_LOAD p_filesz of the retail ELF

AS_FLAGS = '-EL -march=r5900 -mabi=o64 -G0 -no-pad-sections -Iinclude'
LD_FLAGS = ('-EL --no-check-sections '
            f'-T {BASENAME}.ld -T undefined_syms_auto.txt -T undefined_funcs_auto.txt -T linker_script_extra.ld')


def run_splat():
    if not (ROOT / TARGET_ROM).exists():
        subprocess.run([sys.executable, 'tools/elf2bin.py', RETAIL_ELF, TARGET_ROM], check=True, cwd=ROOT)
    subprocess.run([sys.executable, 'tools/gen_symbol_addrs.py'], check=True, cwd=ROOT)
    subprocess.run([sys.executable, '-m', 'splat', 'split', YAML], check=True, cwd=ROOT)
    fix_splat_quirks()


def fix_splat_quirks():
    """Per-function .s files differ from the whole-file ones in two ways that change the assembled bytes:
    the VU0 accumulator is written as bare `ACC` (gas needs `$ACC`), and `%lo(sym + 0x44000)` comes out as
    `%lo(sym + (0x44000 & 0xFFFF))`, which loses the carry that the matching `%hi` needs."""
    acc = re.compile(r'(?<![$\w])ACC(?!\w)')
    # VU0 special registers (Q, I, P, R) in the last operand of a vector op, e.g. `vmaddq.xyzw $vf11, $vf10, Q`
    vureg = re.compile(r'^(\s*(?:/\*.*?\*/)?\s*v[a-z0-9.]+\s+(?:[^\n]*,\s*)?)([QIPR])(?=\s*(?:,|$|/\*))', re.M)
    lo = re.compile(r'(%lo\([^()]*?\+\s*)\((0x[0-9A-Fa-f]+) & 0xFFFF\)\)')
    for f in (ROOT / 'asm/nonmatchings').rglob('*.s'):
        text = f.read_text()
        fixed = vureg.sub(r'\g<1>$\g<2>',lo.sub(r'\g<1>\g<2>)', acc.sub('$ACC', text)))
        if fixed != text:
            f.write_text(fixed)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--split', action='store_true', help='re-run splat before generating build.ninja')
    args = ap.parse_args()

    if args.split or not (ROOT / 'asm').exists():
        run_splat()

    # The splat linker script is the source of truth for which objects exist.
    objs = sorted(set(re.findall(r'(build/\S+?\.o)\(', (ROOT / f'{BASENAME}.ld').read_text())))
    lines = [
        '# Generated by configure.py, do not edit',
        f'cross = {CROSS}',
        f'asflags = {AS_FLAGS}',
        f'ldflags = {LD_FLAGS}',
        '',
        'rule as',
        '  command = ${cross}as $asflags -o $out $in',
        '  description = AS $in',
        '',
        # C/C++: ee-gcc (SN ProDG 2.95.2) via tools/cc.sh; INCLUDE_ASM pulls asm/nonmatchings/<tu>/*.s
        'rule cc',
        f'  command = PYTHON={sys.executable} sh tools/cc.sh $in $out',
        '  description = CC $in',
        '',
        'rule ld',
        '  command = ${cross}ld $ldflags -Map $map -o $out',
        '  description = LD $out',
        '',
        # The retail PT_LOAD ends right after .sdata; splat's ALIGN(128) after the last section adds padding.
        'rule objcopy',
        f'  command = ${{cross}}objcopy -O binary --gap-fill=0x00 $in $out && truncate -s {RETAIL_ROM_SIZE:#x} $out',
        '  description = OBJCOPY $out',
        '',
        'rule check',
        f'  command = sha1sum -c {BASENAME}.sha1 && touch $out',
        '  description = CHECK $in',
        '',
    ]
    headers = ' '.join(sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / 'include').rglob('*.h')))
    for o in objs:
        stem = o[len('build/'):-len('.o')]
        if stem.startswith('src/'):
            src = next((f'{stem}{ext}' for ext in ('.cpp', '.c') if (ROOT / f'{stem}{ext}').exists()), None)
            if src is None:
                sys.exit(f'missing source for {o}')
            nm = ROOT / 'asm/nonmatchings' / stem[len('src/'):]
            deps = sorted(p.relative_to(ROOT).as_posix().replace('$', '$$') for p in nm.glob('*.s')) if nm.is_dir() else []
            lines.append(f'build {o}: cc {src} | tools/cc.sh tools/snfix.py include/macro.inc {headers} {" ".join(deps)}')
        else:
            lines.append(f'build {o}: as {stem}.s | include/macro.inc include/labels.inc')
    elf = f'build/{BASENAME}.elf'
    rom = f'build/{BASENAME}.rom'
    lines += [
        '',
        f'build {elf}: ld | {" ".join(objs)} {BASENAME}.ld',
        f'  map = build/{BASENAME}.map',
        f'build {rom}: objcopy {elf}',
        f'build build/ok: check {rom}',
        'default build/ok',
        '',
    ]
    (ROOT / 'build.ninja').write_text('\n'.join(lines), newline='\n')
    print(f'build.ninja written ({len(objs)} objects)')


if __name__ == '__main__':
    main()
