#!/usr/bin/env python3
"""Generate build.ninja for the WoTM decomp. Run inside WSL/Linux.

    python3 configure.py            # write build.ninja (runs splat first if asm/ is missing)
    python3 configure.py --split    # force a fresh splat split
    ninja                           # build + checksum against the retail binary
"""
import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).parent
YAML = 'SCUS_971.97.yaml'
BASENAME = 'SCUS_971.97'
TARGET_ROM = f'{BASENAME}.rom'
RETAIL_ELF = 'disc/SCUS_971.97'
CROSS = 'mips-linux-gnu-'
RETAIL_ROM_SIZE = 0x5F8B44  # PT_LOAD p_filesz of the retail ELF

AS_FLAGS = '-EL -march=r5900 -mabi=o64 -G0 -no-pad-sections -Iinclude'
LD_FLAGS = ('-EL --no-check-sections '
            f'-T {BASENAME}.ld -T undefined_syms_auto.txt -T undefined_funcs_auto.txt -T linker_script_extra.ld')


def run_splat():
    if not (ROOT / TARGET_ROM).exists():
        subprocess.run([sys.executable, 'tools/elf2bin.py', RETAIL_ELF, TARGET_ROM], check=True, cwd=ROOT)
    subprocess.run([sys.executable, 'tools/gen_symbol_addrs.py'], check=True, cwd=ROOT)
    subprocess.run([sys.executable, '-m', 'splat', 'split', YAML], check=True, cwd=ROOT)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--split', action='store_true', help='re-run splat before generating build.ninja')
    args = ap.parse_args()

    if args.split or not (ROOT / 'asm').exists():
        run_splat()

    asm_files = sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / 'asm').rglob('*.s'))
    objs = []
    lines = [
        '# Generated by configure.py, do not edit',
        f'cross = {CROSS}',
        f'asflags = {AS_FLAGS}',
        f'ldflags = {LD_FLAGS}',
        '',
        'rule as',
        '  command = ${cross}as $asflags -o $out $in',
        '  description = AS $in',
        '',
        'rule ld',
        '  command = ${cross}ld $ldflags -Map $map -o $out',
        '  description = LD $out',
        '',
        # The retail PT_LOAD ends right after .sdata; splat's ALIGN(128) after the last section adds padding.
        'rule objcopy',
        f'  command = ${{cross}}objcopy -O binary --gap-fill=0x00 $in $out && truncate -s {RETAIL_ROM_SIZE:#x} $out',
        '  description = OBJCOPY $out',
        '',
        'rule check',
        f'  command = sha1sum -c {BASENAME}.sha1 && touch $out',
        '  description = CHECK $in',
        '',
    ]
    for s in asm_files:
        o = 'build/' + s[:-2] + '.o'
        objs.append(o)
        lines.append(f'build {o}: as {s} | include/macro.inc include/labels.inc')
    elf = f'build/{BASENAME}.elf'
    rom = f'build/{BASENAME}.rom'
    lines += [
        '',
        f'build {elf}: ld | {" ".join(objs)} {BASENAME}.ld',
        f'  map = build/{BASENAME}.map',
        f'build {rom}: objcopy {elf}',
        f'build build/ok: check {rom}',
        'default build/ok',
        '',
    ]
    (ROOT / 'build.ninja').write_text('\n'.join(lines), newline='\n')
    print(f'build.ninja written ({len(objs)} objects)')


if __name__ == '__main__':
    main()
