// Generated by tools/stabs2h.py from the stabs in hieri.cpp (.mdebug). Do not edit.
#ifndef PS2_SDK_TYPES_H
#define PS2_SDK_TYPES_H


struct ThreadParam;
struct SemaParam;
struct T_COUNT;
struct T_MODE;
struct T_COMP;
struct T_HOLD;
struct IPU_CMD_write;
struct IPU_CMD_read;
struct IPU_TOP;
struct IPU_CTRL;
struct IPU_BP;
struct GIF_CTRL;
struct GIF_MODE;
struct GIF_STAT;
struct GIF_TAG0;
struct GIF_TAG1;
struct GIF_TAG2;
struct GIF_TAG3;
struct GIF_CNT;
struct GIF_P3CNT;
struct GIF_P3TAG;
struct VIF0_STAT;
struct VIF0_FBRST;
struct VIF0_ERR;
struct VIF_MARK;
struct VIF_CYCLE;
struct VIF_MODE;
struct VIF0_NUM;
struct VIF_MASK;
struct VIF_CODE;
struct VIF_ITOPS;
struct VIF_ITOP;
struct VIF_R0;
struct VIF_R1;
struct VIF_R2;
struct VIF_R3;
struct VIF_C0;
struct VIF_C1;
struct VIF_C2;
struct VIF_C3;
struct VIF1_STAT;
struct VIF1_FBRST;
struct VIF1_ERR;
struct VIF1_NUM;
struct VIF1_BASE;
struct VIF1_OFST;
struct VIF1_TOPS;
struct VIF1_TOP;
struct D_CHCR;
struct D_MADR;
struct D_QWC;
struct D_TADR;
struct D_ASR0;
struct D_ASR1;
struct D_SADR;
struct D_CTRL;
struct D_STAT;
struct D_PCR;
struct D_SQWC;
struct D_RBSR;
struct D_RBOR;
struct D_STADR;
struct D_ENABLER;
struct D_ENABLEW;
struct GS_PMODE;
struct GS_SMODE2;
struct GS_DISPFB1;
struct GS_DISPLAY1;
struct GS_DISPFB2;
struct GS_DISPLAY2;
struct GS_EXTBUF;
struct GS_EXTDATA;
struct GS_EXTWRITE;
struct GS_BGCOLOR;
struct GS_CSR;
struct GS_IMR;
struct GS_BUSDIR;
struct GS_SIGLBLID;
struct _sceDmaTag;
struct sceDmaEnv;
struct sceDmaChan;



typedef unsigned char u_char;
typedef unsigned short u_short;
typedef unsigned u_int;
typedef unsigned long u_long;
typedef long long long128;
typedef unsigned long long u_long128;
typedef _sceDmaTag sceDmaTag;

struct ThreadParam {
    int status;  // 0x0
    void *entry;  // 0x4
    void *stack;  // 0x8
    int stackSize;  // 0xC
    void *gpReg;  // 0x10
    int initPriority;  // 0x14
    int currentPriority;  // 0x18
    u_int attr;  // 0x1C
    u_int option;  // 0x20
    int waitType;  // 0x24
    int waitId;  // 0x28
    int wakeupCount;  // 0x2C
};
typedef char _size_ThreadParam[sizeof(ThreadParam) == 48 ? 1 : -1];

struct SemaParam {
    int currentCount;  // 0x0
    int maxCount;  // 0x4
    int initCount;  // 0x8
    int numWaitThreads;  // 0xC
    u_int attr;  // 0x10
    u_int option;  // 0x14
};
typedef char _size_SemaParam[sizeof(SemaParam) == 24 ? 1 : -1];

struct T_COUNT {
    unsigned COUNT : 16;  // 0x0.0
    unsigned p0 : 16;  // 0x2.0
};
typedef char _size_T_COUNT[sizeof(T_COUNT) == 4 ? 1 : -1];

struct T_MODE {
    unsigned CLKS : 2;  // 0x0.0
    unsigned GATE : 1;  // 0x0.2
    unsigned GATS : 1;  // 0x0.3
    unsigned GATM : 2;  // 0x0.4
    unsigned ZRET : 1;  // 0x0.6
    unsigned CUE : 1;  // 0x0.7
    unsigned CMPE : 1;  // 0x1.0
    unsigned OVFE : 1;  // 0x1.1
    unsigned EQUF : 1;  // 0x1.2
    unsigned OVFF : 1;  // 0x1.3
    unsigned p0 : 20;  // 0x1.4
};
typedef char _size_T_MODE[sizeof(T_MODE) == 4 ? 1 : -1];

struct T_COMP {
    unsigned COMP : 16;  // 0x0.0
    unsigned p0 : 16;  // 0x2.0
};
typedef char _size_T_COMP[sizeof(T_COMP) == 4 ? 1 : -1];

struct T_HOLD {
    unsigned HOLD : 16;  // 0x0.0
    unsigned p0 : 16;  // 0x2.0
};
typedef char _size_T_HOLD[sizeof(T_HOLD) == 4 ? 1 : -1];

struct IPU_CMD_write {
    unsigned OPTION : 28;  // 0x0.0
    unsigned CODE : 4;  // 0x3.4
};
typedef char _size_IPU_CMD_write[sizeof(IPU_CMD_write) == 4 ? 1 : -1];

struct IPU_CMD_read {
    unsigned DATA;  // 0x0
    unsigned p0 : 31;  // 0x4.0
    unsigned BUSY : 1;  // 0x7.7
};
typedef char _size_IPU_CMD_read[sizeof(IPU_CMD_read) == 8 ? 1 : -1];

struct IPU_TOP {
    unsigned BSTOP;  // 0x0
    unsigned p0 : 31;  // 0x4.0
    unsigned BUSY : 1;  // 0x7.7
};
typedef char _size_IPU_TOP[sizeof(IPU_TOP) == 8 ? 1 : -1];

struct IPU_CTRL {
    unsigned IFC : 4;  // 0x0.0
    unsigned OFC : 4;  // 0x0.4
    unsigned CBP : 6;  // 0x1.0
    unsigned ECD : 1;  // 0x1.6
    unsigned SCD : 1;  // 0x1.7
    unsigned IDP : 2;  // 0x2.0
    unsigned p0 : 2;  // 0x2.2
    unsigned AS : 1;  // 0x2.4
    unsigned IVF : 1;  // 0x2.5
    unsigned QST : 1;  // 0x2.6
    unsigned MP1 : 1;  // 0x2.7
    unsigned PCT : 3;  // 0x3.0
    unsigned p1 : 3;  // 0x3.3
    unsigned RST : 1;  // 0x3.6
    unsigned BUSY : 1;  // 0x3.7
};
typedef char _size_IPU_CTRL[sizeof(IPU_CTRL) == 4 ? 1 : -1];

struct IPU_BP {
    unsigned BP : 7;  // 0x0.0
    unsigned p0 : 1;  // 0x0.7
    unsigned IFC : 4;  // 0x1.0
    unsigned p1 : 4;  // 0x1.4
    unsigned FP : 2;  // 0x2.0
    unsigned p2 : 14;  // 0x2.2
};
typedef char _size_IPU_BP[sizeof(IPU_BP) == 4 ? 1 : -1];

struct GIF_CTRL {
    unsigned RST : 1;  // 0x0.0
    unsigned p0 : 2;  // 0x0.1
    unsigned PSE : 1;  // 0x0.3
    unsigned p1 : 28;  // 0x0.4
};
typedef char _size_GIF_CTRL[sizeof(GIF_CTRL) == 4 ? 1 : -1];

struct GIF_MODE {
    unsigned M3R : 1;  // 0x0.0
    unsigned p0 : 1;  // 0x0.1
    unsigned IMT : 1;  // 0x0.2
    unsigned p1 : 29;  // 0x0.3
};
typedef char _size_GIF_MODE[sizeof(GIF_MODE) == 4 ? 1 : -1];

struct GIF_STAT {
    unsigned M3R : 1;  // 0x0.0
    unsigned M3P : 1;  // 0x0.1
    unsigned IMT : 1;  // 0x0.2
    unsigned PSE : 1;  // 0x0.3
    unsigned p0 : 1;  // 0x0.4
    unsigned IP3 : 1;  // 0x0.5
    unsigned P3Q : 1;  // 0x0.6
    unsigned P2Q : 1;  // 0x0.7
    unsigned P1Q : 1;  // 0x1.0
    unsigned OPH : 1;  // 0x1.1
    unsigned APATH : 2;  // 0x1.2
    unsigned DIR : 1;  // 0x1.4
    unsigned p1 : 11;  // 0x1.5
    unsigned FQC : 5;  // 0x3.0
    unsigned p2 : 3;  // 0x3.5
};
typedef char _size_GIF_STAT[sizeof(GIF_STAT) == 4 ? 1 : -1];

struct GIF_TAG0 {
    unsigned NLOOP : 15;  // 0x0.0
    unsigned EOP : 1;  // 0x1.7
    unsigned tag : 16;  // 0x2.0
};
typedef char _size_GIF_TAG0[sizeof(GIF_TAG0) == 4 ? 1 : -1];

struct GIF_TAG1 {
    unsigned tag : 14;  // 0x0.0
    unsigned PRE : 1;  // 0x1.6
    unsigned PRIM : 11;  // 0x1.7
    unsigned FLG : 2;  // 0x3.2
    unsigned NREG : 4;  // 0x3.4
};
typedef char _size_GIF_TAG1[sizeof(GIF_TAG1) == 4 ? 1 : -1];

struct GIF_TAG2 {
    unsigned tag;  // 0x0
};
typedef char _size_GIF_TAG2[sizeof(GIF_TAG2) == 4 ? 1 : -1];

struct GIF_TAG3 {
    unsigned tag;  // 0x0
};
typedef char _size_GIF_TAG3[sizeof(GIF_TAG3) == 4 ? 1 : -1];

struct GIF_CNT {
    unsigned LOOPCNT : 15;  // 0x0.0
    unsigned p0 : 1;  // 0x1.7
    unsigned REGCNT : 4;  // 0x2.0
    unsigned VUADDR : 10;  // 0x2.4
    unsigned p1 : 2;  // 0x3.6
};
typedef char _size_GIF_CNT[sizeof(GIF_CNT) == 4 ? 1 : -1];

struct GIF_P3CNT {
    unsigned P3CNT : 15;  // 0x0.0
    unsigned p0 : 17;  // 0x1.7
};
typedef char _size_GIF_P3CNT[sizeof(GIF_P3CNT) == 4 ? 1 : -1];

struct GIF_P3TAG {
    unsigned LOOPCNT : 15;  // 0x0.0
    unsigned EOP : 1;  // 0x1.7
    unsigned p0 : 16;  // 0x2.0
};
typedef char _size_GIF_P3TAG[sizeof(GIF_P3TAG) == 4 ? 1 : -1];

struct VIF0_STAT {
    unsigned VPS : 2;  // 0x0.0
    unsigned VEW : 1;  // 0x0.2
    unsigned p0 : 3;  // 0x0.3
    unsigned MRK : 1;  // 0x0.6
    unsigned p1 : 1;  // 0x0.7
    unsigned VSS : 1;  // 0x1.0
    unsigned VFS : 1;  // 0x1.1
    unsigned VIS : 1;  // 0x1.2
    unsigned INT : 1;  // 0x1.3
    unsigned ERO : 1;  // 0x1.4
    unsigned ER1 : 1;  // 0x1.5
    unsigned p2 : 10;  // 0x1.6
    unsigned FQC : 4;  // 0x3.0
    unsigned p3 : 4;  // 0x3.4
};
typedef char _size_VIF0_STAT[sizeof(VIF0_STAT) == 4 ? 1 : -1];

struct VIF0_FBRST {
    unsigned RST : 1;  // 0x0.0
    unsigned FBK : 1;  // 0x0.1
    unsigned STP : 1;  // 0x0.2
    unsigned STC : 1;  // 0x0.3
    unsigned p0 : 28;  // 0x0.4
};
typedef char _size_VIF0_FBRST[sizeof(VIF0_FBRST) == 4 ? 1 : -1];

struct VIF0_ERR {
    unsigned MII : 1;  // 0x0.0
    unsigned ME0 : 1;  // 0x0.1
    unsigned ME1 : 1;  // 0x0.2
    unsigned p0 : 29;  // 0x0.3
};
typedef char _size_VIF0_ERR[sizeof(VIF0_ERR) == 4 ? 1 : -1];

struct VIF_MARK {
    unsigned MARK : 16;  // 0x0.0
    unsigned p0 : 16;  // 0x2.0
};
typedef char _size_VIF_MARK[sizeof(VIF_MARK) == 4 ? 1 : -1];

struct VIF_CYCLE {
    unsigned CL : 8;  // 0x0.0
    unsigned WL : 8;  // 0x1.0
    unsigned p0 : 16;  // 0x2.0
};
typedef char _size_VIF_CYCLE[sizeof(VIF_CYCLE) == 4 ? 1 : -1];

struct VIF_MODE {
    unsigned MOD : 2;  // 0x0.0
    unsigned p0 : 30;  // 0x0.2
};
typedef char _size_VIF_MODE[sizeof(VIF_MODE) == 4 ? 1 : -1];

struct VIF0_NUM {
    unsigned num : 8;  // 0x0.0
    unsigned p0 : 24;  // 0x1.0
};
typedef char _size_VIF0_NUM[sizeof(VIF0_NUM) == 4 ? 1 : -1];

struct VIF_MASK {
    unsigned m0 : 2;  // 0x0.0
    unsigned m1 : 2;  // 0x0.2
    unsigned m2 : 2;  // 0x0.4
    unsigned m3 : 2;  // 0x0.6
    unsigned m4 : 2;  // 0x1.0
    unsigned m5 : 2;  // 0x1.2
    unsigned m6 : 2;  // 0x1.4
    unsigned m7 : 2;  // 0x1.6
    unsigned m8 : 2;  // 0x2.0
    unsigned m9 : 2;  // 0x2.2
    unsigned m10 : 2;  // 0x2.4
    unsigned m11 : 2;  // 0x2.6
    unsigned m12 : 2;  // 0x3.0
    unsigned m13 : 2;  // 0x3.2
    unsigned m14 : 2;  // 0x3.4
    unsigned m15 : 2;  // 0x3.6
};
typedef char _size_VIF_MASK[sizeof(VIF_MASK) == 4 ? 1 : -1];

struct VIF_CODE {
    unsigned immediate : 16;  // 0x0.0
    unsigned num : 8;  // 0x2.0
    unsigned CMD : 8;  // 0x3.0
};
typedef char _size_VIF_CODE[sizeof(VIF_CODE) == 4 ? 1 : -1];

struct VIF_ITOPS {
    unsigned ITOPS : 10;  // 0x0.0
    unsigned p0 : 22;  // 0x1.2
};
typedef char _size_VIF_ITOPS[sizeof(VIF_ITOPS) == 4 ? 1 : -1];

struct VIF_ITOP {
    unsigned ITOP : 10;  // 0x0.0
    unsigned p0 : 22;  // 0x1.2
};
typedef char _size_VIF_ITOP[sizeof(VIF_ITOP) == 4 ? 1 : -1];

struct VIF_R0 {
    unsigned R0;  // 0x0
};
typedef char _size_VIF_R0[sizeof(VIF_R0) == 4 ? 1 : -1];

struct VIF_R1 {
    unsigned R1;  // 0x0
};
typedef char _size_VIF_R1[sizeof(VIF_R1) == 4 ? 1 : -1];

struct VIF_R2 {
    unsigned R2;  // 0x0
};
typedef char _size_VIF_R2[sizeof(VIF_R2) == 4 ? 1 : -1];

struct VIF_R3 {
    unsigned R3;  // 0x0
};
typedef char _size_VIF_R3[sizeof(VIF_R3) == 4 ? 1 : -1];

struct VIF_C0 {
    unsigned C0;  // 0x0
};
typedef char _size_VIF_C0[sizeof(VIF_C0) == 4 ? 1 : -1];

struct VIF_C1 {
    unsigned C1;  // 0x0
};
typedef char _size_VIF_C1[sizeof(VIF_C1) == 4 ? 1 : -1];

struct VIF_C2 {
    unsigned C2;  // 0x0
};
typedef char _size_VIF_C2[sizeof(VIF_C2) == 4 ? 1 : -1];

struct VIF_C3 {
    unsigned C3;  // 0x0
};
typedef char _size_VIF_C3[sizeof(VIF_C3) == 4 ? 1 : -1];

struct VIF1_STAT {
    unsigned VPS : 2;  // 0x0.0
    unsigned VEW : 1;  // 0x0.2
    unsigned VGW : 1;  // 0x0.3
    unsigned p0 : 2;  // 0x0.4
    unsigned MRK : 1;  // 0x0.6
    unsigned DBF : 1;  // 0x0.7
    unsigned VSS : 1;  // 0x1.0
    unsigned VFS : 1;  // 0x1.1
    unsigned VIS : 1;  // 0x1.2
    unsigned INT : 1;  // 0x1.3
    unsigned ERO : 1;  // 0x1.4
    unsigned ER1 : 1;  // 0x1.5
    unsigned p1 : 9;  // 0x1.6
    unsigned FDR : 1;  // 0x2.7
    unsigned FQC : 5;  // 0x3.0
    unsigned p2 : 3;  // 0x3.5
};
typedef char _size_VIF1_STAT[sizeof(VIF1_STAT) == 4 ? 1 : -1];

struct VIF1_FBRST {
    unsigned RST : 1;  // 0x0.0
    unsigned FBK : 1;  // 0x0.1
    unsigned STP : 1;  // 0x0.2
    unsigned STC : 1;  // 0x0.3
    unsigned p0 : 28;  // 0x0.4
};
typedef char _size_VIF1_FBRST[sizeof(VIF1_FBRST) == 4 ? 1 : -1];

struct VIF1_ERR {
    unsigned MII : 1;  // 0x0.0
    unsigned ME0 : 1;  // 0x0.1
    unsigned ME1 : 1;  // 0x0.2
    unsigned p0 : 29;  // 0x0.3
};
typedef char _size_VIF1_ERR[sizeof(VIF1_ERR) == 4 ? 1 : -1];

struct VIF1_NUM {
    unsigned num : 8;  // 0x0.0
    unsigned p0 : 24;  // 0x1.0
};
typedef char _size_VIF1_NUM[sizeof(VIF1_NUM) == 4 ? 1 : -1];

struct VIF1_BASE {
    unsigned BASE : 10;  // 0x0.0
    unsigned p0 : 22;  // 0x1.2
};
typedef char _size_VIF1_BASE[sizeof(VIF1_BASE) == 4 ? 1 : -1];

struct VIF1_OFST {
    unsigned OFFSET : 10;  // 0x0.0
    unsigned p0 : 22;  // 0x1.2
};
typedef char _size_VIF1_OFST[sizeof(VIF1_OFST) == 4 ? 1 : -1];

struct VIF1_TOPS {
    unsigned TOPS : 10;  // 0x0.0
    unsigned p0 : 22;  // 0x1.2
};
typedef char _size_VIF1_TOPS[sizeof(VIF1_TOPS) == 4 ? 1 : -1];

struct VIF1_TOP {
    unsigned TOP : 10;  // 0x0.0
    unsigned p0 : 22;  // 0x1.2
};
typedef char _size_VIF1_TOP[sizeof(VIF1_TOP) == 4 ? 1 : -1];

struct D_CHCR {
    unsigned DIR : 1;  // 0x0.0
    unsigned p0 : 1;  // 0x0.1
    unsigned MOD : 2;  // 0x0.2
    unsigned ASP : 2;  // 0x0.4
    unsigned TTE : 1;  // 0x0.6
    unsigned TIE : 1;  // 0x0.7
    unsigned STR : 1;  // 0x1.0
    unsigned p1 : 7;  // 0x1.1
    unsigned TAG : 16;  // 0x2.0
};
typedef char _size_D_CHCR[sizeof(D_CHCR) == 4 ? 1 : -1];

struct D_MADR {
    unsigned ADDR : 31;  // 0x0.0
    unsigned SPR : 1;  // 0x3.7
};
typedef char _size_D_MADR[sizeof(D_MADR) == 4 ? 1 : -1];

struct D_QWC {
    unsigned QWC : 16;  // 0x0.0
    unsigned p0 : 16;  // 0x2.0
};
typedef char _size_D_QWC[sizeof(D_QWC) == 4 ? 1 : -1];

struct D_TADR {
    unsigned ADDR : 31;  // 0x0.0
    unsigned SPR : 1;  // 0x3.7
};
typedef char _size_D_TADR[sizeof(D_TADR) == 4 ? 1 : -1];

struct D_ASR0 {
    unsigned ADDR : 31;  // 0x0.0
    unsigned SPR : 1;  // 0x3.7
};
typedef char _size_D_ASR0[sizeof(D_ASR0) == 4 ? 1 : -1];

struct D_ASR1 {
    unsigned ADDR : 31;  // 0x0.0
    unsigned SPR : 1;  // 0x3.7
};
typedef char _size_D_ASR1[sizeof(D_ASR1) == 4 ? 1 : -1];

struct D_SADR {
    unsigned ADDR : 14;  // 0x0.0
    unsigned p0 : 18;  // 0x1.6
};
typedef char _size_D_SADR[sizeof(D_SADR) == 4 ? 1 : -1];

struct D_CTRL {
    unsigned DMAE : 1;  // 0x0.0
    unsigned RELE : 1;  // 0x0.1
    unsigned MFD : 2;  // 0x0.2
    unsigned STS : 2;  // 0x0.4
    unsigned STD : 2;  // 0x0.6
    unsigned RCYC : 3;  // 0x1.0
    unsigned p0 : 21;  // 0x1.3
};
typedef char _size_D_CTRL[sizeof(D_CTRL) == 4 ? 1 : -1];

struct D_STAT {
    unsigned CIS0 : 1;  // 0x0.0
    unsigned CIS1 : 1;  // 0x0.1
    unsigned CIS2 : 1;  // 0x0.2
    unsigned CIS3 : 1;  // 0x0.3
    unsigned CIS4 : 1;  // 0x0.4
    unsigned CIS5 : 1;  // 0x0.5
    unsigned CIS6 : 1;  // 0x0.6
    unsigned CIS7 : 1;  // 0x0.7
    unsigned CIS8 : 1;  // 0x1.0
    unsigned CIS9 : 1;  // 0x1.1
    unsigned p0 : 3;  // 0x1.2
    unsigned SIS : 1;  // 0x1.5
    unsigned MEIS : 1;  // 0x1.6
    unsigned BEIS : 1;  // 0x1.7
    unsigned CIM0 : 1;  // 0x2.0
    unsigned CIM1 : 1;  // 0x2.1
    unsigned CIM2 : 1;  // 0x2.2
    unsigned CIM3 : 1;  // 0x2.3
    unsigned CIM4 : 1;  // 0x2.4
    unsigned CIM5 : 1;  // 0x2.5
    unsigned CIM6 : 1;  // 0x2.6
    unsigned CIM7 : 1;  // 0x2.7
    unsigned CIM8 : 1;  // 0x3.0
    unsigned CIM9 : 1;  // 0x3.1
    unsigned p1 : 3;  // 0x3.2
    unsigned SIM : 1;  // 0x3.5
    unsigned MEIM : 1;  // 0x3.6
    unsigned p2 : 1;  // 0x3.7
};
typedef char _size_D_STAT[sizeof(D_STAT) == 4 ? 1 : -1];

struct D_PCR {
    unsigned CPC0 : 1;  // 0x0.0
    unsigned CPC1 : 1;  // 0x0.1
    unsigned CPC2 : 1;  // 0x0.2
    unsigned CPC3 : 1;  // 0x0.3
    unsigned CPC4 : 1;  // 0x0.4
    unsigned CPC5 : 1;  // 0x0.5
    unsigned CPC6 : 1;  // 0x0.6
    unsigned CPC7 : 1;  // 0x0.7
    unsigned CPC8 : 1;  // 0x1.0
    unsigned CPC9 : 1;  // 0x1.1
    unsigned p0 : 6;  // 0x1.2
    unsigned CDE0 : 1;  // 0x2.0
    unsigned CDE1 : 1;  // 0x2.1
    unsigned CDE2 : 1;  // 0x2.2
    unsigned CDE3 : 1;  // 0x2.3
    unsigned CDE4 : 1;  // 0x2.4
    unsigned CDE5 : 1;  // 0x2.5
    unsigned CDE6 : 1;  // 0x2.6
    unsigned CDE7 : 1;  // 0x2.7
    unsigned CDE8 : 1;  // 0x3.0
    unsigned CDE9 : 1;  // 0x3.1
    unsigned p1 : 5;  // 0x3.2
    unsigned PCE : 1;  // 0x3.7
};
typedef char _size_D_PCR[sizeof(D_PCR) == 4 ? 1 : -1];

struct D_SQWC {
    unsigned SQWC : 8;  // 0x0.0
    unsigned p0 : 8;  // 0x1.0
    unsigned TQWC : 8;  // 0x2.0
    unsigned p1 : 8;  // 0x3.0
};
typedef char _size_D_SQWC[sizeof(D_SQWC) == 4 ? 1 : -1];

struct D_RBSR {
    unsigned RMSK : 31;  // 0x0.0
    unsigned p0 : 1;  // 0x3.7
};
typedef char _size_D_RBSR[sizeof(D_RBSR) == 4 ? 1 : -1];

struct D_RBOR {
    unsigned ADDR : 31;  // 0x0.0
    unsigned p0 : 1;  // 0x3.7
};
typedef char _size_D_RBOR[sizeof(D_RBOR) == 4 ? 1 : -1];

struct D_STADR {
    unsigned ADDR : 31;  // 0x0.0
    unsigned p0 : 1;  // 0x3.7
};
typedef char _size_D_STADR[sizeof(D_STADR) == 4 ? 1 : -1];

struct D_ENABLER {
    unsigned p0 : 16;  // 0x0.0
    unsigned CPND : 1;  // 0x2.0
    unsigned p1 : 15;  // 0x2.1
};
typedef char _size_D_ENABLER[sizeof(D_ENABLER) == 4 ? 1 : -1];

struct D_ENABLEW {
    unsigned p0 : 16;  // 0x0.0
    unsigned CPND : 1;  // 0x2.0
    unsigned p1 : 15;  // 0x2.1
};
typedef char _size_D_ENABLEW[sizeof(D_ENABLEW) == 4 ? 1 : -1];

struct GS_PMODE {
    unsigned EN1 : 1;  // 0x0.0
    unsigned EN2 : 1;  // 0x0.1
    unsigned CRTMD : 3;  // 0x0.2
    unsigned MMOD : 1;  // 0x0.5
    unsigned AMOD : 1;  // 0x0.6
    unsigned SLBG : 1;  // 0x0.7
    unsigned ALP : 8;  // 0x1.0
    unsigned p0 : 16;  // 0x2.0
    unsigned p1;  // 0x4
};
typedef char _size_GS_PMODE[sizeof(GS_PMODE) == 8 ? 1 : -1];

struct GS_SMODE2 {
    unsigned INT : 1;  // 0x0.0
    unsigned FFMD : 1;  // 0x0.1
    unsigned DPMS : 2;  // 0x0.2
    unsigned p0 : 28;  // 0x0.4
    unsigned p1;  // 0x4
};
typedef char _size_GS_SMODE2[sizeof(GS_SMODE2) == 8 ? 1 : -1];

struct GS_DISPFB1 {
    unsigned FBP : 9;  // 0x0.0
    unsigned FBW : 6;  // 0x1.1
    unsigned PSM : 5;  // 0x1.7
    unsigned p0 : 12;  // 0x2.4
    unsigned DBX : 11;  // 0x4.0
    unsigned DBY : 11;  // 0x5.3
    unsigned p1 : 10;  // 0x6.6
};
typedef char _size_GS_DISPFB1[sizeof(GS_DISPFB1) == 8 ? 1 : -1];

struct GS_DISPLAY1 {
    unsigned DX : 12;  // 0x0.0
    unsigned DY : 11;  // 0x1.4
    unsigned MAGH : 4;  // 0x2.7
    unsigned MAGV : 2;  // 0x3.3
    unsigned p0 : 3;  // 0x3.5
    unsigned DW : 12;  // 0x4.0
    unsigned DH : 11;  // 0x5.4
    unsigned p1 : 9;  // 0x6.7
};
typedef char _size_GS_DISPLAY1[sizeof(GS_DISPLAY1) == 8 ? 1 : -1];

struct GS_DISPFB2 {
    unsigned FBP : 9;  // 0x0.0
    unsigned FBW : 6;  // 0x1.1
    unsigned PSM : 5;  // 0x1.7
    unsigned p0 : 12;  // 0x2.4
    unsigned DBX : 11;  // 0x4.0
    unsigned DBY : 11;  // 0x5.3
    unsigned p1 : 10;  // 0x6.6
};
typedef char _size_GS_DISPFB2[sizeof(GS_DISPFB2) == 8 ? 1 : -1];

struct GS_DISPLAY2 {
    unsigned DX : 12;  // 0x0.0
    unsigned DY : 11;  // 0x1.4
    unsigned MAGH : 4;  // 0x2.7
    unsigned MAGV : 2;  // 0x3.3
    unsigned p0 : 3;  // 0x3.5
    unsigned DW : 12;  // 0x4.0
    unsigned DH : 11;  // 0x5.4
    unsigned p1 : 9;  // 0x6.7
};
typedef char _size_GS_DISPLAY2[sizeof(GS_DISPLAY2) == 8 ? 1 : -1];

struct GS_EXTBUF {
    unsigned EXBP : 14;  // 0x0.0
    unsigned EXBW : 6;  // 0x1.6
    unsigned FBIN : 2;  // 0x2.4
    unsigned WFFMD : 1;  // 0x2.6
    unsigned EMODA : 2;  // 0x2.7
    unsigned EMODC : 2;  // 0x3.1
    unsigned p0 : 5;  // 0x3.3
    unsigned WDX : 11;  // 0x4.0
    unsigned WDY : 11;  // 0x5.3
    unsigned p1 : 10;  // 0x6.6
};
typedef char _size_GS_EXTBUF[sizeof(GS_EXTBUF) == 8 ? 1 : -1];

struct GS_EXTDATA {
    unsigned SX : 12;  // 0x0.0
    unsigned SY : 11;  // 0x1.4
    unsigned SMPH : 4;  // 0x2.7
    unsigned SMPV : 2;  // 0x3.3
    unsigned p0 : 3;  // 0x3.5
    unsigned WW : 12;  // 0x4.0
    unsigned WH : 11;  // 0x5.4
    unsigned p1 : 9;  // 0x6.7
};
typedef char _size_GS_EXTDATA[sizeof(GS_EXTDATA) == 8 ? 1 : -1];

struct GS_EXTWRITE {
    unsigned WRITE : 1;  // 0x0.0
    unsigned p0 : 31;  // 0x0.1
    unsigned p1;  // 0x4
};
typedef char _size_GS_EXTWRITE[sizeof(GS_EXTWRITE) == 8 ? 1 : -1];

struct GS_BGCOLOR {
    unsigned R : 8;  // 0x0.0
    unsigned G : 8;  // 0x1.0
    unsigned B : 8;  // 0x2.0
    unsigned p0 : 8;  // 0x3.0
    unsigned p1;  // 0x4
};
typedef char _size_GS_BGCOLOR[sizeof(GS_BGCOLOR) == 8 ? 1 : -1];

struct GS_CSR {
    unsigned SIGNAL : 1;  // 0x0.0
    unsigned FINISH : 1;  // 0x0.1
    unsigned HSINT : 1;  // 0x0.2
    unsigned VSINT : 1;  // 0x0.3
    unsigned EDWINT : 1;  // 0x0.4
    unsigned p0 : 3;  // 0x0.5
    unsigned FLUSH : 1;  // 0x1.0
    unsigned RESET : 1;  // 0x1.1
    unsigned p1 : 2;  // 0x1.2
    unsigned NFIELD : 1;  // 0x1.4
    unsigned FIELD : 1;  // 0x1.5
    unsigned FIFO : 2;  // 0x1.6
    unsigned REV : 8;  // 0x2.0
    unsigned ID : 8;  // 0x3.0
    unsigned p2;  // 0x4
};
typedef char _size_GS_CSR[sizeof(GS_CSR) == 8 ? 1 : -1];

struct GS_IMR {
    unsigned p0 : 8;  // 0x0.0
    unsigned SIGMSK : 1;  // 0x1.0
    unsigned FINISHMSK : 1;  // 0x1.1
    unsigned HSMSK : 1;  // 0x1.2
    unsigned VSMSK : 1;  // 0x1.3
    unsigned EDWMSK : 1;  // 0x1.4
    unsigned p1 : 19;  // 0x1.5
    unsigned p2;  // 0x4
};
typedef char _size_GS_IMR[sizeof(GS_IMR) == 8 ? 1 : -1];

struct GS_BUSDIR {
    unsigned DIR : 1;  // 0x0.0
    unsigned p0 : 31;  // 0x0.1
    unsigned p1;  // 0x4
};
typedef char _size_GS_BUSDIR[sizeof(GS_BUSDIR) == 8 ? 1 : -1];

struct GS_SIGLBLID {
    unsigned SIGID;  // 0x0
    unsigned LBLID;  // 0x4
};
typedef char _size_GS_SIGLBLID[sizeof(GS_SIGLBLID) == 8 ? 1 : -1];

struct _sceDmaTag {
    u_short qwc;  // 0x0
    u_char mark;  // 0x2
    u_char id;  // 0x3
    _sceDmaTag *next;  // 0x4
    unsigned p[2];  // 0x8
};
typedef char _size__sceDmaTag[sizeof(_sceDmaTag) == 16 ? 1 : -1];

struct sceDmaEnv {
    u_char sts;  // 0x0
    u_char std;  // 0x1
    u_char mfd;  // 0x2
    u_char rcycle;  // 0x3
    u_short express;  // 0x4
    u_short notify;  // 0x6
    u_short sqwc;  // 0x8
    u_short tqwc;  // 0xA
    void *rbadr;  // 0xC
    u_int rbmsk;  // 0x10
};
typedef char _size_sceDmaEnv[sizeof(sceDmaEnv) == 20 ? 1 : -1];

struct sceDmaChan {
    D_CHCR chcr;  // 0x0
    unsigned p0[3];  // 0x4
    void *madr;  // 0x10
    unsigned p1[3];  // 0x14
    u_int qwc;  // 0x20
    unsigned p2[3];  // 0x24
    sceDmaTag *tadr;  // 0x30
    unsigned p3[3];  // 0x34
    void *as0;  // 0x40
    unsigned p4[3];  // 0x44
    void *as1;  // 0x50
    unsigned p5[3];  // 0x54
    unsigned p6[4];  // 0x60
    unsigned p7[4];  // 0x70
    void *sadr;  // 0x80
    unsigned p8[3];  // 0x84
};
typedef char _size_sceDmaChan[sizeof(sceDmaChan) == 144 ? 1 : -1];

#endif
