"""Generate splat symbol_addrs.txt from the retail ELF's .symtab (the ELF ships unstripped)."""
import collections, sys
from elftools.elf.elffile import ELFFile

elf_path = sys.argv[1] if len(sys.argv) > 1 else 'disc/SCUS_971.97'
out_path = sys.argv[2] if len(sys.argv) > 2 else 'symbol_addrs.txt'

with open(elf_path, 'rb') as f:
    elf = ELFFile(f)
    secs = {i: s.name for i, s in enumerate(elf.iter_sections())}
    entries = {}
    for s in elf.get_section_by_name('.symtab').iter_symbols():
        typ = s['st_info']['type']
        if typ not in ('STT_FUNC', 'STT_OBJECT') or not s.name or not isinstance(s['st_shndx'], int):
            continue
        if secs[s['st_shndx']] in ('.vutext', '.vudata', '.vubss') or s['st_value'] < 0x100000:
            continue  # VU microcode lives in its own address space
        entries.setdefault(s['st_value'], (s.name, typ, s['st_size'], s['st_info']['bind']))

# Local symbols can share names across TUs; make each unique by suffixing the address.
counts = collections.Counter(n for n, *_ in entries.values())
with open(out_path, 'w', newline='\n') as out:
    out.write('// Generated by tools/gen_symbol_addrs.py from the retail ELF symtab. Do not edit by hand;\n')
    out.write('// put manual additions in symbol_addrs_manual.txt instead.\n')
    for addr in sorted(entries):
        name, typ, size, bind = entries[addr]
        if counts[name] > 1:
            name = f'{name}_{addr:08X}'
        attrs = ['type:func'] if typ == 'STT_FUNC' else []
        if size:
            attrs.append(f'size:0x{size:X}')
        attrs = ' '.join(attrs)
        out.write(f'{name} = 0x{addr:08X}; // {attrs}\n')
print(f'wrote {len(entries)} symbols to {out_path}')
