"""Find %hi/%lo pairs that spimdisasm resolved into the middle of .text and force them to raw immediates.

Some game code builds large struct offsets with `lui 0x12` etc.; spimdisasm pairs these into
`%hi(.L00120380)`, which links only while everything sits in one file. We emit MIPS_NONE relocs
(raw immediates) into reloc_addrs.txt. Run after a split, then split again.
"""
import re, struct
from pathlib import Path

TEXT_START, TEXT_END = 0x100000, 0x251020
LINE = re.compile(r'/\* ([0-9A-F]+) ([0-9A-F]{8}) ([0-9A-F]{8}) \*/\s+\S+\s.*%(hi|lo)\(((?:\.L|D_|jtbl_)([0-9A-F]{8}))\)')

relocs = {}
for path in sorted(Path('asm').rglob('*.s')):
    for line in path.read_text().splitlines():
        m = LINE.search(line)
        if not m:
            continue
        target = int(m.group(6), 16)
        if not TEXT_START <= target < TEXT_END:
            continue
        rom = int(m.group(1), 16)
        word = struct.unpack('<I', bytes.fromhex(m.group(3)))[0]
        imm = word & 0xFFFF
        if m.group(4) == 'lo' and imm & 0x8000:
            imm -= 0x10000
        value = f'-0x{-imm:X}' if imm < 0 else f'0x{imm:X}'
        relocs[rom] = f'rom:0x{rom:06X} reloc:MIPS_NONE symbol:{value} // was %{m.group(4)}({m.group(5)}) in {path.as_posix()}'

existing = {}
p = Path('reloc_addrs.txt')
if p.exists():
    for line in p.read_text().splitlines():
        m = re.match(r'rom:0x([0-9A-F]+)', line)
        if m:
            existing[int(m.group(1), 16)] = line
existing.update(relocs)
p.write_text('// Generated by tools/gen_relocs.py\n' + '\n'.join(existing[k] for k in sorted(existing)) + '\n', newline='\n')
print(f'{len(relocs)} new, {len(existing)} total relocs in reloc_addrs.txt')
